version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: stars_backend
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - ./uploads:/app/uploads
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: stars_frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev

  nginx:
    image: nginx:1.24.0
    container_name: stars_nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./src/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
